module.exports = [
  {
    team: 'Orioles',
    city: 'Baltimore',
    state: 'MD',
    league: 'AL',
  },
  {
    team: 'Red Sox',
    city: 'Boston',
    state: 'MA',
    league: 'AL',
  },
  {
    team: 'White Sox',
    city: 'Chicago',
    state: 'IL',
    league: 'AL',
  },
  {
    team: 'Indians',
    city: 'Cleveland',
    state: 'OH',
    league: 'AL',
  },
  {
    team: 'Tigers',
    city: 'Detroit',
    state: 'MI',
    league: 'AL',
  },
  {
    team: 'Astros',
    city: 'Houston',
    state: 'TX',
    league: 'AL',
  },
  {
    team: 'Royals',
    city: 'Kansas City',
    state: 'MO',
    league: 'AL',
  },
  {
    team: 'Angels',
    city: 'Los Angeles',
    state: 'CA',
    league: 'AL',
  },
  {
    team: 'Yankees',
    city: 'Bronx',
    state: 'NY',
    league: 'AL',
  },
  {
    team: 'Athletics',
    city: 'Oakland',
    state: 'CA',
    league: 'AL',
  },
  {
    team: 'Mariners',
    city: 'Seattle',
    state: 'WA',
    league: 'AL',
  },
  {
    team: 'Rays',
    city: 'St.Petersburg',
    state: 'FL',
    league: 'AL',
  },
  {
    team: 'Rangers',
    city: 'Arlington',
    state: 'TX',
    league: 'AL',
  },
  {
    team: 'Blue Jays',
    city: 'Toronto',
    state: 'Ontario, CAN',
    league: 'AL',
  },
  {
    team: 'Diamondbacks',
    city: 'Phoenix',
    state: 'AZ',
    league: 'NL',
  },
  {
    team: 'Braves',
    city: 'Atlanta',
    state: 'GA',
    league: 'NL',
  },
  {
    team: 'Cubs',
    city: 'Chicago',
    state: 'IL',
    league: 'NL',
  },
  {
    team: 'Reds',
    city: 'Cincinnati',
    state: 'OH',
    league: 'NL',
  },
  {
    team: 'Rockies',
    city: 'Denver',
    state: 'CO',
    league: 'NL',
  },
  {
    team: 'Dodgers',
    city: 'Los Angeles',
    state: 'CA',
    league: 'NL',
  },
  {
    team: 'Marlins',
    city: 'Miami',
    state: 'FL',
    league: 'NL',
  },
  {
    team: 'Brewers',
    city: 'Milwaukee',
    state: 'WI',
    league: 'NL',
  },
  {
    team: 'Mets',
    city: 'Corona',
    state: 'NY',
    league: 'NL',
  },
  {
    team: 'Phillies',
    city: 'Philadelphia',
    state: 'PA',
    league: 'NL',
  },
  {
    team: 'Pirates',
    city: 'Pittsburgh',
    state: 'PA',
    league: 'NL',
  },
  {
    team: 'Padres',
    city: 'San Diego',
    state: 'CA',
    league: 'NL',
  },
  {
    team: 'Giants',
    city: 'San Francisco',
    state: 'CA',
    league: 'NL',
  },
  {
    team: 'Cardinals',
    city: 'St. Louis',
    state: 'MO',
    league: 'NL',
  },
  {
    team: 'Nationals',
    city: 'Washington',
    state: 'DC',
    league: 'NL',
  },
  {
    team: 'Twins',
    city: 'Minneapolis',
    state: 'MN',
    league: 'AL',
  },
  {
    team: 'changed mid-season',
    city: 'none',
    state: 'none',
    league: 'none',
  }
];
